# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1393501027);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1393501147);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1393568886);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 552960);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20120606065243");
user_pref("browser.startup.homepage_override.mstone", "rv:10.0.5");
user_pref("browser.syncPromoViewsLeft", 4);
user_pref("browser.tabs.warnOnClose", false);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 11);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:10.0.5");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1390736445000}}}]");
user_pref("extensions.lastAppVersion", "10.0.5");
user_pref("extensions.lastPlatformVersion", "10.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 2);
user_pref("gfx.blacklist.suggested-driver-version", "<Anything with EXT_texture_from_pixmap support>");
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.msaa", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("idle.lastDailyNotification", 1393501432);
user_pref("intl.charsetmenu.browser.cache", "GB2312, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1393501432);
user_pref("places.history.expiration.transient_current_max_pages", 25926);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1392088340);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1394677214);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
